### ISSUE TITLE
deis auth:regenerate panic after v2.3.0 -> v2.4.0 upgrade

### ISSUE THREAD

**Issue by seanknox** [deis/controller-sdk-go#81] opened 2016-08-19 04:24 UTC
Steps to reproduce:
- Install Workflow v2.3.0
- Upgrade to v2.4.0
- `deis apps` returns: `Error: Unauthorized: Missing or Invalid Token`
- Run `deis auth:regenerate` 

```
○ → deis auth:regenerate
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x160881]

goroutine 1 [running]:
panic(0x4e12a0, 0xc82000e100)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/deis/workflow-cli/vendor/github.com/deis/controller-sdk-go/auth.Regenerate.func1(0x0)
	/go/src/github.com/deis/workflow-cli/vendor/github.com/deis/controller-sdk-go/auth/auth.go:110 +0xb1
panic(0x4e12a0, 0xc82000e100)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/deis/workflow-cli/vendor/github.com/deis/controller-sdk-go/auth.Regenerate(0xc8202100e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/deis/workflow-cli/vendor/github.com/deis/controller-sdk-go/auth/auth.go:119 +0x4a1
github.com/deis/workflow-cli/cmd.Regenerate(0x0, 0x0, 0xc82011dc00, 0x0, 0x0)
	/go/src/github.com/deis/workflow-cli/cmd/auth.go:279 +0xa4
github.com/deis/workflow-cli/parser.authRegenerate(0xc82006e090, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/deis/workflow-cli/parser/auth.go:238 +0x290
github.com/deis/workflow-cli/parser.Auth(0xc82006e090, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/deis/workflow-cli/parser/auth.go:40 +0x686
main.Command(0xc82006e090, 0x1, 0x1, 0x1a20b5)
	/go/src/github.com/deis/workflow-cli/deis.go:93 +0xe47
main.main()
	/go/src/github.com/deis/workflow-cli/deis.go:18 +0x60
```

```
cat ~/.deis/client.json
{"username":"admin","ssl_verify":false,"controller":"http://deis.example.com","token":"eb648a2fb4d5b9b8dccffd88ae585b84f4b5c475","response_limit":0}
```

**Comment by Joshua-Anderson** [comment] 2016-08-19 16:29
Was able to reproduce.

`deis auth:regenerate` works properly when logged in, but panics if you have an invalid token.

I'll investigate this.
In the meantime @seanknox, logging in again before running `deis auth:regenerate` should fix the problem.

**Comment by seanknox** [comment] 2016-08-19 16:33
Thanks @Joshua-Anderson, logging in again does take care of it.

**Comment by Joshua-Anderson** [comment] 2016-08-19 20:39
Found the source of the bug: https://github.com/deis/controller-sdk-go/blob/master/auth/auth.go#L105

```
if err != nil && !deis.IsErrAPIMismatch(reqErr) {
		return "", reqErr
}
```

should actually be

```
if reqErr != nil && !deis.IsErrAPIMismatch(reqErr) {
		return "", reqErr
}
```

Once I get CI working for this repository I'll PR a fix for this.

**Comment by think01** [comment] 2016-08-26 10:50
Hello.
I'm experiencing same issue, so I'm waiting for the fix :o)
In the meantime, I'm not sure how to use the suggested workaround. If I logout (with `deis auth:logout`) and then login again, with `deis auth:login http://deis.10.3.0.182.nip.io`, I get this error:
`Error: Unable to log in with provided credentials.`
Of course I'm double-sure provided credentials were correct.

In order to avoid the issue, I must re-register a new user but of course I loose access to previous apps (and login to old users doesn't work anymore).

Does anyone have any help, please?

Thanks in advance,
Fabio

**Comment by Joshua-Anderson** [comment] 2016-08-26 15:40
@think01 If you would like to talk to someone to help debug this, I'm happy to help in the [deis community slack channel](http://slack.deis.io/). If you're using minio for your data storage (the default option), I suspect it was restarted, resulting in the loss of all data on your cluster. This would explain why you are no longer able to log in because your cluster state would have been entirely reset.

**Closed** 2016-08-26 20:25 UTC
Labels: bug, in progress

**Comment by think01** [comment] 2016-08-29 12:33
Thank you @Joshua-Anderson!
Anyway, I had this problem with:

    coreos-kubernetes (with kubernetes 1.3.4)
    vagrant 1.8.5

It disappeared using kubernetes 1.3.5 (without CoreOs, as per the official Deis tutorial) and Vagrant 1.8.3 (there's a regression in Vagrant: https://github.com/mitchellh/vagrant/issues/5186).
